apiVersion: v1
kind: Service
metadata:
  name: {{SERVICE}}
  labels: 
    run: {{SERVICE}}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: {{SERVICE}}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{SERVICE}}
  labels:
    app: {{SERVICE}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{SERVICE}}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: {{SERVICE}}
    spec:
      containers:
        - name: {{SERVICE}}
          image: {{IMAGE_TAG}}
          ports:
          - containerPort: 8000
          command: ["/server"]
          volumeMounts:
            - name: config-volume
              mountPath: /conf
      volumes:
       - name: config-volume
         projected:
           defaultMode: 420
           sources:
           - configMap:
               items:
               - key: app.conf
                 path: app.conf
               name: {{SERVICE}}-config
